export const projects = [
  {
    title: 'Dokkōdō',
    description: "A minimalist website that can display Musashi's 21 principles for those who walk alone in this life.",
      tags: ['JavaScript', 'CSS'],
    source: 'https://github.com/ayoub3bidi/Dokkodo',
    visit: 'https://ayoub3bidi.github.io/Dokkodo',
    id: 0,
  },
  {
    title: 'My Favorite LOL Champion',
    description: "A minimalist website for my favorite League of Legends champion Ekko.",
      tags: ['Bootstrap'],
    source: 'https://github.com/ayoub3bidi/myFavoriteLolChampion',
    visit: 'https://ayoub3bidi.github.io/myFavoriteLolChampion',
    id: 1,
  },
  {
    title: 'Quotes',
    description:"A website that can display random inspirational quotes from a public Api.",
    tags: ['JavaScript', 'Bootstrap', 'Public API'],
    source: 'https://github.com/ayoub3bidi/Quotes',
    visit: 'https://ayoub3bidi.github.io/Quotes',
    id: 2,
  },
  {
    title: 'My Heroes',
    description: "A minimalist website that can display mini-biographies about 20 programmers who made the internet as we know it today.",
      tags: ['Vue', 'Bootstrap'],
    source: 'https://github.com/ayoub3bidi/myheroes',
    visit: 'https://ayoub3bidi.github.io/myheroes/',
    id: 3,
  },
  {
    title: `My List`,
    description: "A simple platform to share your passion by creating lists and sharing them with other users. [Summer internship project]",
    tags: ['Vue', 'Bootstrap', 'Firebase'],
    source: 'https://github.com/ayoub3bidi/mylist',
    visit: 'https://mylist-f82d6.firebaseapp.com',
    id: 4,
  },
  {
    title: `Time Check`,
    description: "Projects management platform. [Freelance project]",
    tags: ['Vue', 'Bootstrap', 'Express', 'Mongo DB'],
    source: '',
    visit: '',
    id: 5,
  },
  {
    title: 'Covid Tracker',
    description: "Covid-19 cases and deaths tracker.",
      tags: ['Vue', 'Tailwind CSS', 'Covid-19 API'],
    source: 'https://github.com/ayoub3bidi/covid-tracker',
    visit: 'https://online-covid-19-tracker.netlify.app/',
    id: 6,
  },
  {
    title: 'Sou9 api',
    description: "An API for e-commerce.",
      tags: ['Express', 'Crypto.js', 'JWT' ,'Mongo DB'],
    source: 'https://github.com/ayoub3bidi/sou9_api',
    visit: '',
    id: 7,
  },
  {
    title: '7amma frippe',
    description: "A React E-commerce web app UI.",
      tags: ['React', 'Styled-components'],
    source: 'https://github.com/ayoub3bidi/7amma-fripe',
    visit: 'https://7amma-fripe.netlify.app',
    id: 8,
  },
  {
    title: 'Podium ESG',
    description: "Financial portfolios publication web app. [End-of-studies internship project]",
      tags: ['Vue','Express', 'PostgreSQL', 'Docker',],
    source: '',
    visit: '',
    id: 9,
  },
  {
    title: 'Ommek Sannefa',
    description: "Kitchen recipes sharing platform.",
      tags: ['Vue', 'VueX' ,'Firebase'],
    source: 'https://github.com/ayoub3bidi/ommek-sannefa',
    visit: '',
    id: 10,
  },
  {
    title: 'Flousi',
    description: "a simple expense tracker web app.",
      tags: ['React', 'Express' ,'Mongo DB'],
    source: 'https://github.com/ayoub3bidi/flousi',
    visit: 'https://flousi.vercel.app/',
    id: 11,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Wyróżnienie jako betatester'}
];
