const experienceData = [
  {
    title: "Full-stack Developer (Freelance)",
    company: "Talaba TN",
    location: "Remote",
    range: "December 2023 - Present",
    url: "https://talabatn.net",
    texts: [
      "Redesigned the public-facing landing page, including animations, bilingual (Arabic/French) support, and multiple content sections to improve user engagement.",
      "Developed a news and announcements system allowing admins to target specific student groups by institute and class, with full content management capabilities.",
      "Built a Lucky Wheel gamification feature from scratch to boost student engagement, with admin controls for prizes, probabilities, and promo code distribution via email.",
      "Implemented a promo code and discount system with usage limits, expiry management, and seamless integration into the student payment flow.",
      "Created profile management screens for students and teachers, including a custom image cropper for profile picture uploads.",
      "Shipped a full e-commerce module for physical and digital products, covering product listings, a checkout flow, and an order management dashboard for admins.",
      "Built an analytics dashboard giving the team visibility into student activity, marketing performance, and complaint tracking.",
      "Developed a teacher resources module enabling teachers to upload and share course materials, with admin controls to activate or deactivate content",
      "Consistently improved platform UX across the app, redesigned authentication pages, unified notification styles, and enhanced the video player with keyboard shortcuts and speed controls.",
      "Added a referral system to support user acquisition and growth initiatives."
    ],
    stack: [
      "JavaScript",
      "React",
      "React Native",
      "Angular",
      "Bootstrap",
      "MUI",
      "Flask",
      "FastAPI",
      "PostgreSQL",
      "Docker",
      "AWS"
    ],
  },
  {
    title: "Full-stack Developer",
    company: "Comwork.io",
    location: "Remote",
    range: "January 2023 - September 2025",
    url: "https://comwork.io",
    texts: [
      "Designed and built an enterprise cloud management platform (CWCloud) with OIDC authentication and multi-tenant architecture.",
      "Led migration from Flask to FastAPI to improve API performance and scalability.",
      "Built production-ready RESTful APIs with comprehensive error handling, logging, and monitoring.",
      "Developed responsive web interfaces with React and mobile applications with Flutter, focusing on improved UX/UI.",
      "Implemented a comprehensive testing strategy (unit, integration, E2E) to increase code quality and reduce production bugs.",
      "Established CI/CD pipelines using GitLab CI/CD and GitHub Actions with automated testing, security scanning, and containerized deployments using Docker.",
      "Led technical reviews to improve code quality and speed up the review process."
    ],
    stack: [
      "Docker",
      "Go",
      "React.js",
      "Blockly",
      "MySQL",
      "Redis",
      "GitLab CI/CD",
      "Axios",
      "Flask",
      "Minio",
      "Docusaurus",
      "FastAPI",
      "Tailwind CSS",
      "Pulumi",
      "JavaScript",
      "Unittest",
      "Jest",
      "MUI",
      "Kubernetes",
      "PostgreSQL",
      "bcrypt",
      "Bootstrap",
      "Flutter",
    ],
  },
  {
    title: "End-of-studies intern",
    company: "Podyam",
    location: "Remote",
    range: "January 2022 - May 2022",
    url: "https://www.podyam.com",
    texts: [
      "Full-stack development of a finance web platform.",
      "Developed interfaces with Vue.js, Quasar, and Bootstrap following Figma design.",
      "Created tables in the PostgreSQL database with ORM migration using Objection.js.",
    ],
    stack: [
      "Docker",
      "Vuex",
      "Figma",
      "Quasar Framework",
      "JavaScript",
      "Vue.js",
      "Express.js",
      "PostgreSQL",
      "Bootstrap",
    ]
  },
  {
    title: "Frontend Developer (Freelance)",
    company: "TuniAOS",
    location: "Remote",
    range: "September 2021 - November 2021",
    url: "http://www.tuniaos.com",
    texts: [
      "Frontend development of a MEVN stack web app.",
      "Created interfaces with Vue.js and Bootstrap.",
      "Consumed data from the API using Axios.",
    ],
    stack: [
      "Axios",
      "JavaScript", 
      "Vue.js",
      "Bootstrap",
    ]
  },
  {
    title: "Summer Intern",
    company: "Tunisie Telecom",
    location: "Remote",
    range: "June 2021 - July 2021",
    url: "https://www.tunisietelecom.tn",
    texts: ["Designed, developed, and deployed a serverless mini-platform."],
    stack: [
      "Adobe XD",
      "Firebase",
      "JavaScript",
      "Vue.js",
      "Bootstrap",
    ]
  },
];

export default experienceData;
