const projectsData = [
  {
    title: 'ovh/cds',
    description: `Enterprise-Grade Continuous Delivery & DevOps Automation Open Source Platform.`,
    type: 'Open-source',
    imgSrc: '',
    href: 'ovh.github.io/cds',
    repo: 'https://github.com/ayoub3bidi/cds/tree/fix/use-environment-variables',
    techStack: ['Go', 'PostgreSQL', 'Redis', 'GRPC', 'Docker'],
    startDate: '2025-10-27',
    endDate: '',
  },
  {
    title: 'Think-iT-Labs/dirhash',
    description: `Compute a deterministic checksum of a directory by hashing file contents and their relative paths.`,
    type: 'Open-source',
    imgSrc: '',
    href: '',
    repo: 'https://github.com/ayoub3bidi/dirhash/tree/feat/modernize-2025',
    techStack: ['Go', 'Cobra CLI', 'GitHub Actions'],
    startDate: '2025-10-07',
    endDate: '',
  },
  // {
  //   title: 'Bayan Flow',
  //   description: `A web app that visualizes algorithms in animated step by step.`,
  //   type: 'Open-source',
  //   imgSrc: '',
  //   href: 'https://bayanflow.netlify.app',
  //   repo: 'https://github.com/ayoub3bidi/bayan-flow',
  //   techStack: ['React', 'Tailwind CSS', 'Framer Motion', 'D3js', 'vitejs', 'vitest'],
  //   startDate: '2025-10-01',
  //   endDate: ''
  // },
  // {
  //   title: 'Sacred Scripts',
  //   description: `A collection of open-source scripts and tools for automating tasks and enhancing productivity.`,
  //   type: 'Open-source',
  //   imgSrc: '',
  //   href: '',
  //   repo: 'https://github.com/ayoub3bidi/sacred-scripts',
  //   techStack: ['Python'],
  //   startDate: '2024-10-06',
  //   endDate: ''
  // },
  {
    title: 'Comwork Cloud MCP',
    description: `A Context Protocol server enabling AI assistants to integrate with Comwork Cloud services`,
    type: 'Comwork.io',
    imgSrc: '',
    href: '',
    repo: 'https://gitlab.comwork.io/oss/cwcloud/cwcloud-mcp',
    techStack: ['Go', 'Logrus', 'Godotenv', 'MCP Protocol'],
    startDate: '2025-08-05',
    endDate: '2025-09-30',
  },
  {
    title: 'Venus',
    description: `A modern documentation website boilerplate powered by Docusaurus and Tailwind CSS.`,
    type: 'Open-source',
    imgSrc: '',
    href: 'https://venus-docs.netlify.app',
    repo: 'https://github.com/ayoub3bidi/venus',
    techStack: ['React', 'Docusaurus', 'Tailwind CSS', 'Docker'],
    startDate: '2025-01-03',
    endDate: '',
  },
  {
    title: 'Talaba TN',
    description: `A Tunisian e-learning platform, dedicated to high school and university students.`,
    type: 'Freelance',
    imgSrc: '',
    href: 'https://talabatn.net',
    repo: '',
    techStack: [
      'React Native',
      'React',
      'AngularJS',
      'Bootstrap',
      'MUI',
      'Lottie Animations',
      'Docker',
      'FastAPI',
      'Flask',
      'PostgreSQL',
    ],
    startDate: '2023-12-16',
    endDate: '',
  },
  {
    title: 'imalive',
    description: `A simple, fast and reliable uptime monitoring service.`,
    type: 'Open-source',
    imgSrc: '',
    href: '',
    repo: 'https://github.com/idrissneumann/imalive',
    techStack: ['Fast API', 'Docker', 'CI/CD'],
    startDate: '2023-10-04',
    endDate: '2025-06-20',
  },
  {
    title: 'Mercury',
    description: `A FastAPI template with PostgreSQL and Redis databases`,
    type: 'Open-source',
    imgSrc: '',
    href: '',
    repo: 'https://github.com/ayoub3bidi/mercury',
    techStack: ['Fast API', 'PostgreSQL', 'Redis', 'Docker'],
    startDate: '2023-10-04',
    endDate: '',
  },
  {
    title: 'Object Detection System',
    description: `A real-time object detection system.`,
    type: 'Academic',
    imgSrc: '',
    href: 'https://ayoub-object-detection.netlify.app',
    repo: 'https://github.com/ayoub3bidi/object_detection',
    techStack: [
      'Python',
      'OpenCV',
      'YOLO',
      'Firebase',
      'GTTS',
      'React',
      'Vite',
    ],
    startDate: '2023-11-01',
    endDate: '2023-12-03',
  },
  {
    title: 'Festival Management System',
    description: `A festival management system.`,
    type: 'Academic',
    imgSrc: '',
    href: '',
    repo: 'https://github.com/ayoub3bidi/gestion_festival',
    techStack: [
      'Next',
      'Redux',
      'Chart.js',
      'Tailwind CSS',
      'TypeScript',
      'FastAPI',
      'PostgreSQL',
      'Redis',
      'Docker',
    ],
    startDate: '2023-10-28',
    endDate: '2023-12-10',
  },
  {
    title: 'Golf App',
    description: `Golf Tee Times management mobile app for dAInamic.`,
    type: 'Comwork.io',
    imgSrc: '',
    href: '',
    repo: '',
    techStack: ['Flutter', 'Firebase'],
    startDate: '2023-07-03',
    endDate: '2023-08-21',
  },
  {
    title: 'Fairmat App',
    description: `Bar code scanning web app for Fairmat factory.`,
    type: 'Comwork.io',
    imgSrc: '',
    href: '',
    repo: '',
    techStack: ['Flutter', 'FastAPI', 'Redis', 'PostgreSQL', 'Docker', 'CI/CD'],
    startDate: '2023-03-11',
    endDate: '2023-07-22',
  },
  {
    title: 'ZAN-f',
    description: `The official ZAN-f wood products website.`,
    type: 'Comwork.io',
    imgSrc: '',
    href: 'https://www.zan-f.com/',
    repo: '',
    techStack: ['React', 'Docusaurus', 'Tailwind CSS'],
    startDate: '2023-05-23',
    endDate: '2023-06-12',
  },
  {
    title: 'Document Control Connector',
    description: `A microservice for Docapost.`,
    type: 'Comwork.io',
    imgSrc: '',
    href: '',
    repo: '',
    techStack: ['Flask', 'Minio', 'Redis', 'MySQL', 'Docker', 'CI/CD'],
    startDate: '2023-02-23',
    endDate: '2023-03-30',
  },
  {
    title: 'Comwork.io',
    description: `The official Comwork.io website.`,
    type: 'Comwork.io',
    imgSrc: '',
    href: 'https://comwork.io',
    repo: '',
    techStack: [
      'React',
      'Docusaurus',
      'Tailwind CSS',
      'Framer Motion',
      'Lottie Animations',
    ],
    startDate: '2023-01-23',
    endDate: '2025-09-30',
  },
  {
    title: 'Comwork Cloud CLI',
    description: `A CLI to use Comwork Cloud API.`,
    type: 'Comwork.io',
    imgSrc: '',
    href: '',
    repo: 'https://gitlab.comwork.io/oss/cwcloud/cwc',
    techStack: ['Go', 'Cobra CLI', 'Docker', 'CI/CD'],
    startDate: '2023-01-23',
    endDate: '2025-06-20',
  },
  {
    title: 'Comwork Cloud',
    description: `A complete, fully functional, local developers or sysadmin environment on the cloud, has been designed to reduce the setup time as well as your hosting costs.`,
    type: 'Comwork.io',
    imgSrc: '',
    href: 'https://www.cwcloud.tech',
    repo: 'https://github.com/comworkio/comwork-cloud-wiki',
    techStack: [
      'React',
      'Docusaurus',
      'Bootstrap',
      'Material UI',
      'Axios',
      'FastAPI',
      'Jinja 2',
      'Pulumi',
      'Minio',
      'Redis',
      'PostgreSQL',
      'Docker',
      'Kubernetes',
      'GitLab CI/CD',
      'Scaleway',
      'AWS',
      'GCP',
    ],
    startDate: '2023-01-23',
    endDate: '2025-09-30',
  },
  {
    title: 'Book Notes',
    description: `Notes from programming books. [Open-source]`,
    type: 'Open-source',
    imgSrc: '',
    href: '',
    repo: 'https://github.com/Tunisian-GitHub-Community/Book-notes',
    techStack: ['React', 'Docusaurus', 'CSS'],
    startDate: '2022-05-18',
    endDate: '',
  },
  {
    title: 'Notes',
    description: `A markdown-supported note-taking web app.`,
    type: 'Open-source',
    imgSrc: '',
    href: '',
    repo: 'https://github.com/ayoub3bidi/ma5zen',
    techStack: ['React', 'TypeScript', 'Bootstrap', 'React-select'],
    startDate: '2022-12-23',
    endDate: '2023-01-05',
  },
  {
    title: 'Ma5zen',
    description: `A full-stack inventory web app.`,
    type: 'Open-source',
    imgSrc: '',
    href: '',
    repo: 'https://github.com/ayoub3bidi/ma5zen',
    techStack: [
      'Next.js',
      'Tailwind CSS',
      'Mantine UI',
      'Prisma',
      'PostgreSQL',
      'Docker',
    ],
    startDate: '2022-12-23',
    endDate: '2023-01-05',
  },
  {
    title: 'Mouzika',
    description: `A Spotify clone.`,
    type: 'Academic',
    imgSrc: '',
    href: 'https://mouzika.netlify.app',
    repo: 'https://github.com/ayoub3bidi/mouzika',
    techStack: ['React', 'Redux', 'Tailwind CSS', 'RapidAPI'],
    startDate: '2022-11-13',
    endDate: '2023-01-04',
  },
  {
    title: 'My Vets',
    description: `A veterinary clinic mobile app.`,
    type: 'Tagamuta Valley',
    imgSrc: '',
    href: 'https://play.google.com/store/apps/details?id=tn.myvetsapp.myvets',
    repo: '',
    techStack: ['Flutter', 'Firebase', 'Spring Boot', 'Kafka'],
    startDate: '2022-10-05',
    endDate: '2022-12-21',
  },
  {
    title: 'Sector R',
    description: `A real-time chatroom.`,
    type: 'Open-source',
    imgSrc: '',
    href: 'https://sector-r.netlify.app',
    repo: 'https://github.com/ayoub3bidi/sector-r',
    techStack: ['React', 'Sass', 'Firebase'],
    startDate: '2022-05-04',
    endDate: '2023-01-19',
  },
  {
    title: 'Reddit Clone',
    description: `A full-stack reddit clone.`,
    type: 'Open-source',
    imgSrc: '',
    href: '',
    repo: 'https://github.com/ayoub3bidi/reddit-clone',
    techStack: [
      'Next',
      'TypeScript',
      'Express',
      'TypeORM',
      'GraphQL',
      'PostgreSQL',
      'Docker',
    ],
    startDate: '2022-06-25',
    endDate: '2022-10-03',
  },
  {
    title: 'Flousi',
    description: `A simple expense tracker web app.`,
    type: 'Open-source',
    imgSrc: '',
    href: 'https://flousi.netlify.app',
    repo: 'https://github.com/ayoub3bidi/flousi',
    techStack: ['React', 'Express', 'MongoDB'],
    startDate: '2022-06-06',
    endDate: '2022-06-19',
  },
  {
    title: 'Ommek Sannefa',
    description: `Kitchen recipes sharing platform.`,
    type: 'Open-source',
    imgSrc: '',
    href: '',
    repo: 'https://github.com/ayoub3bidi/ommek-sannefa',
    techStack: ['Vue', 'VueX', 'Firebase'],
    startDate: '2022-05-02',
    endDate: '2022-06-05',
  },
  {
    title: 'Podium ESG (End-of-studies internship project) ',
    description: `Financial portfolios publication web app.`,
    type: 'Academic',
    imgSrc: '',
    href: '',
    repo: '',
    techStack: [
      'Vue',
      'Bootstrap',
      'Quasar',
      'Express',
      'Objection.js',
      'PostgreSQL',
      'Docker',
    ],
    startDate: '2022-01-20',
    endDate: '2022-05-26',
  },
  {
    title: 'Koujina API',
    description: `An API for kitchen recipes.`,
    type: 'Open-source',
    imgSrc: '',
    href: '',
    repo: 'https://github.com/Tunisian-GitHub-Community/Koujina_api',
    techStack: ['Express', 'JWT', 'Bcrypt.js', 'MongoDB'],
    startDate: '2022-01-16',
    endDate: '2022-10-06',
  },
  {
    title: 'Sou9 API',
    description: `An API for e-commerce.`,
    type: 'Open-source',
    imgSrc: '',
    href: '',
    repo: 'https://github.com/ayoub3bidi/sou9_api',
    techStack: ['Express', 'JWT', 'Crypto.js', 'MongoDB'],
    startDate: '2022-01-23',
    endDate: '2022-10-06',
  },
  {
    title: 'Covid Tracker',
    description: `Covid-19 cases and deaths tracker.`,
    type: 'Open-source',
    imgSrc: '',
    href: 'https://online-covid-19-tracker.netlify.app',
    repo: 'https://github.com/ayoub3bidi/covid-tracker',
    techStack: ['Vue', 'Tailwind CSS', 'Covid-19 API'],
    startDate: '2022-01-16',
    endDate: '2022-01-20',
  },
  {
    title: 'Time Check',
    description: `Projects management mini-platform.`,
    type: 'Freelance',
    imgSrc: '',
    href: '',
    repo: '',
    techStack: ['MongoDB', 'Express', 'Vue', 'Node', 'Bootstrap'],
    startDate: '2021-09-12',
    endDate: '2021-11-05',
  },
  {
    title: 'My List (Summer internship project)',
    description: `A simple platform to share your passion by creating lists and sharing them with other users.`,
    type: 'Academic',
    imgSrc: '',
    href: 'https://mylist-f82d6.firebaseapp.com',
    repo: 'https://github.com/ayoub3bidi/mylist',
    techStack: ['Vue', 'Bootstrap', 'Firebase'],
    startDate: '2021-06-19',
    endDate: '2021-07-11',
  },
  {
    title: 'GFA Phones',
    description: `A simple e-commerce platform for phones and accessories.`,
    type: 'Academic',
    imgSrc: '',
    href: '',
    repo: 'https://github.com/ayoub3bidi/GFA-phones',
    techStack: [
      'Angular',
      'Bootstrap ',
      'Adobe XD',
      'Balsamique',
      'FastAPI',
      'MySQL',
    ],
    startDate: '2021-02-03',
    endDate: '2021-04-22',
  },
  {
    title: 'My Heroes',
    description: `A minimalist website that can display mini-biographies about 20 programmers who made the internet as we know it today.`,
    type: 'Open-source',
    imgSrc: '',
    href: 'https://ayoub3bidi.github.io/myheroes/',
    repo: 'https://github.com/ayoub3bidi/myheroes',
    techStack: ['Vue', 'Bootstrap'],
    startDate: '2021-03-17',
    endDate: '2021-03-19',
  },
  {
    title: 'Quotes',
    description: `A website that can display random inspirational quotes from a public Api.`,
    type: 'Open-source',
    imgSrc: '',
    href: 'https://ayoub3bidi.github.io/Quotes',
    repo: 'https://github.com/ayoub3bidi/Quotes',
    techStack: ['Bootstrap', 'Javascript', 'Public API'],
    startDate: '2021-03-15',
    endDate: '2021-03-15',
  },
  {
    title: 'My Favorite LOL Champion',
    description: `A minimalist website for my favorite League of Legends champion Ekko.`,
    type: 'Open-source',
    imgSrc: '',
    href: 'https://ayoub3bidi.github.io/myFavoriteLolChampion/',
    repo: 'https://github.com/ayoub3bidi/myFavoriteLolChampion',
    techStack: ['HTML', 'Bootstrap', 'Javascript'],
    startDate: '2021-01-17',
    endDate: '2021-03-14',
  },
  {
    title: 'Dokkōdō',
    description: `A minimalist website that can display Musashi's 21 principles for those who walk alone in this life.`,
    type: 'Open-source',
    imgSrc: '',
    href: 'https://ayoub3bidi.github.io/Dokkodo',
    repo: 'https://github.com/ayoub3bidi/Dokkodo',
    techStack: ['JavaScript', 'CSS', 'Webslides'],
    startDate: '2021-01-19',
    endDate: '2021-03-13',
  },
]

export default projectsData
