const projectsData = [
    {
      title: 'DirHash',
      description: `Compute a deterministic checksum of a directory by hashing file contents and their relative paths, with support for glob-based exclusions and symbolic link navigation.`,
      type: 'Open-source',
      imgSrc: '',
      href: '',
      github: 'https://github.com/ayoub3bidi/dirhash/tree/feat/modernize-2025',
      techStack: ['Go', 'Cobra CLI', 'GitHub Actions'],
    },
    // {
    //   title: 'Algorithm Visualizer',
    //   description: `A web app that visualizes algorithms in animated step by step.`,
    //   type: 'Open-source',
    //   imgSrc: '',
    //   href: 'https://algoviz-app.netlify.app',
    //   github: 'https://github.com/ayoub3bidi/algorithm-visualizer',
    //   techStack: ['React', 'Tailwind CSS', 'Framer Motion', 'D3js', 'vitejs', 'vitest'],
    // },
    // {
    //   title: 'Sacred Scripts',
    //   description: `A collection of open-source scripts and tools for automating tasks and enhancing productivity.`,
    //   type: 'Open-source',
    //   imgSrc: '',
    //   href: '',
    //   github: 'https://github.com/ayoub3bidi/sacred-scripts',
    //   techStack: ['Python']
    // },
    {
      title: 'Comwork Cloud MCP',
      description: `A Context Protocol server enabling AI assistants to integrate with Comwork Cloud services`,
      type: 'Comwork.io',
      imgSrc: '',
      href: '',
      github: 'https://gitlab.comwork.io/oss/cwcloud/cwcloud-mcp',
      techStack: ['Go', 'Logrus', 'Godotenv', 'MCP Protocol'],
    },
    {
      title: 'Janus',
      description: `A modern documentation website boilerplate powered by Docusaurus and Tailwind CSS.`,
      type: 'Open-source',
      imgSrc: '',
      href: 'https://janus-docs.vercel.app',
      github: 'https://github.com/ayoub3bidi/janus',
      techStack: ['React', 'Docusaurus', 'Tailwind CSS', 'Docker', 'CI/CD'],
    },
    {
      title: 'Talaba TN',
      description: `A Tunisian e-learning platform, dedicated to high school and university students.`,
      type: 'Freelance',
      imgSrc: '',
      href: 'https://talabatn.net',
      github: '',
      techStack: ["React Native", 'React', "AngularJS", "Bootstrap", "MUI", "Lottie Animations", "Docker", "FastAPI", "Flask", "PostgreSQL"],
    },
    {
      title: 'imalive',
      description: `A simple, fast and reliable uptime monitoring service.`,
      type: 'Open-source',
      imgSrc: '',
      href: '',
      github: 'https://github.com/idrissneumann/imalive',
      techStack: ['Fast API', 'Docker', 'CI/CD'],
    },
    {
      title: 'Mercury',
      description: `A FastAPI template with PostgreSQL and Redis databases`,
      type: 'Open-source',
      imgSrc: '',
      href: '',
      github: 'https://github.com/ayoub3bidi/mercury',
      techStack: ['Fast API', 'PostgreSQL', 'Redis', 'Docker'],
    },
    {
      title: 'Object Detection System',
      description: `A real-time object detection system.`,
      type: 'Academic',
      imgSrc: '',
      href: 'https://ayoub-object-detection.vercel.app',
      github: 'https://github.com/ayoub3bidi/object_detection',
      techStack: ['Python', 'OpenCV', 'YOLO', 'Firebase', "GTTS", "React", "Vite"],
    },
    {
      title: 'Festival Management System',
      description: `A festival management system.`,
      type: 'Academic',
      imgSrc: '',
      href: '',
      github: 'https://github.com/ayoub3bidi/gestion_festival',
      techStack: ['Next', 'Redux', 'Chart.js', 'Tailwind CSS', 'TypeScript', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker'],
    },
    {
      title: 'Golf App',
      description: `Golf Tee Times management mobile app for dAInamic.`,
      type: 'Comwork.io',
      imgSrc: '',
      href: '',
      github: '',
      techStack: ['Flutter', 'Firebase'],
    },
    {
      title: 'Fairmat App',
      description: `Bar code scanning web app for Fairmat factory.`,
      type: 'Comwork.io',
      imgSrc: '',
      href: '',
      github: '',
      techStack: ['Flutter', 'FastAPI', 'Redis', 'PostgreSQL', 'Docker', 'CI/CD'],
    },
    {
      title: 'ZAN-f',
      description: `The official ZAN-f wood products website.`,
      type: 'Comwork.io',
      imgSrc: '',
      href: 'https://www.zan-f.com/',
      github: '',
      techStack: ['React', 'Docusaurus', 'Tailwind CSS'],
    },
    {
      title: 'Document Control Connector',
      description: `A microservice for Docapost.`,
      type: 'Comwork.io',
      imgSrc: '',
      href: '',
      github: '',
      techStack: ['Flask', 'Minio', 'Redis', 'MySQL', 'Docker', 'CI/CD'],
    },
    {
      title: 'Comwork.io',
      description: `The official Comwork.io website.`,
      type: 'Comwork.io',
      imgSrc: '',
      href: 'https://comwork.io',
      github: '',
      techStack: ['React', 'Docusaurus', 'Tailwind CSS', 'Framer Motion', 'Lottie Animations'],
    },
    {
      title: 'Comwork Cloud CLI',
      description: `A CLI to use Comwork Cloud API.`,
      type: 'Comwork.io',
      imgSrc: '',
      href: '',
      github: 'https://gitlab.comwork.io/oss/cwcloud/cwc',
      techStack: ['Go', 'Cobra CLI', 'Docker', 'CI/CD'],
    },
    {
      title: 'Comwork Cloud',
      description: `A complete, fully functional, local developers or sysadmin environment on the cloud, has been designed to reduce the setup time as well as your hosting costs.`,
      type: 'Comwork.io',
      imgSrc: '',
      href: 'https://www.cwcloud.tech',
      github: 'https://github.com/comworkio/comwork-cloud-wiki',
      techStack: ['React', 'Docusaurus', 'Bootstrap', 'Material UI', 'Axios', 'FastAPI', 'Jinja 2', 'Pulumi', 'Minio', 'Redis', 'PostgreSQL', 'Docker', 'Kubernetes', 'GitLab CI/CD','Scaleway', 'AWS', 'GCP'],
    },
    {
      title: 'Book Notes',
      description: `Notes from programming books. [Open-source]`,
      type: 'Open-source',
      imgSrc: '',
      href: 'https://book-notes.vercel.app/',
      github: 'https://github.com/Tunisian-GitHub-Community/Book-notes',
      techStack: ['React', 'Docusaurus', 'CSS'],
    },
    {
      title: 'Notes',
      description: `A markdown-supported note-taking web app.`,
      type: 'Open-source',
      imgSrc: '',
      href: '',
      github: 'https://github.com/ayoub3bidi/ma5zen',
      techStack: ['React', 'TypeScript', 'Bootstrap', 'React-select'],
    },
    {
      title: 'Ma5zen',
      description: `A full-stack inventory web app.`,
      type: 'Open-source',
      imgSrc: '',
      href: '',
      github: 'https://github.com/ayoub3bidi/ma5zen',
      techStack: ['Next.js', 'Tailwind CSS', 'Mantine UI', 'Prisma', 'PostgreSQL', 'Docker'],
    },
    {
      title: 'Mouzika',
      description: `A Spotify clone.`,
      type: 'Academic',
      imgSrc: '',
      href: 'https://mouzika.vercel.app',
      github: 'https://github.com/ayoub3bidi/mouzika',
      techStack: ['React', 'Redux', 'Tailwind CSS', 'RapidAPI'],
    },
    {
      title: 'Vets',
      description: `A veterinary clinic mobile app.`,
      type: 'Tagamuta Valley',
      imgSrc: '',
      href: '',
      github: '',
      techStack: ['Flutter', 'Firebase', 'Spring Boot', 'Kafka'],
    },
    {
      title: 'Sector R',
      description: `A real-time chatroom.`,
      type: 'Open-source',
      imgSrc: '',
      href: 'https://sector-r.vercel.app',
      github: 'https://github.com/ayoub3bidi/sector-r',
      techStack: ['React', 'Sass', 'Firebase'],
    },
    {
      title: 'Reddit Clone',
      description: `A full-stack reddit clone.`,
      type: 'Open-source',
      imgSrc: '',
      href: '',
      github: 'https://github.com/ayoub3bidi/reddit-clone',
      techStack: ['Next', 'TypeScript', 'Express', 'TypeORM', 'GraphQL', 'PostgreSQL', 'Docker'],
    },
    {
      title: 'Flousi',
      description: `A simple expense tracker web app.`,
      type: 'Open-source',
      imgSrc: '',
      href: 'https://flousi.vercel.app',
      github: 'https://github.com/ayoub3bidi/flousi',
      techStack: ['React', 'Express', 'MongoDB'],
    },
    {
      title: 'Ommek Sannefa',
      description: `Kitchen recipes sharing platform.`,
      type: 'Open-source',
      imgSrc: '',
      href: '',
      github: 'https://github.com/ayoub3bidi/ommek-sannefa',
      techStack: ['Vue', 'VueX', 'Firebase'],
    },
    {
      title: 'Podium ESG (End-of-studies internship project) ',
      description: `Financial portfolios publication web app.`,
      type: 'Academic',
      imgSrc: '',
      href: '',
      github: '',
      techStack: ['Vue', 'Bootstrap', 'Quasar', 'Express', 'Objection.js', 'PostgreSQL', 'Docker'],
    },
    {
      title: 'Koujina API',
      description: `An API for kitchen recipes.`,
      type: 'Open-source',
      imgSrc: '',
      href: '',
      github: 'https://github.com/Tunisian-GitHub-Community/Koujina_api',
      techStack: ['Express', 'JWT', 'Bcrypt.js', 'MongoDB'],
    },
    {
      title: 'Sou9 API',
      description: `An API for e-commerce.`,
      type: 'Open-source',
      imgSrc: '',
      href: '',
      github: 'https://github.com/pycoder2000/Stock-Management',
      techStack: ['Express', 'JWT', 'Crypto.js', 'MongoDB'],
    },
    {
      title: 'Covid Tracker',
      description: `Covid-19 cases and deaths tracker.`,
      type: 'Open-source',
      imgSrc: '',
      href: 'https://online-covid-19-tracker.netlify.app',
      github: 'https://github.com/ayoub3bidi/covid-tracker',
      techStack: ['Vue', 'Tailwind CSS', 'Covid-19 API'],
    },
    {
      title: 'Time Check',
      description: `Projects management mini-platform.`,
      type: 'Freelance',
      imgSrc: '',
      href: '',
      github: '',
      techStack: ['MongoDB', 'Express', 'Vue', 'Node', 'Bootstrap'],
    },
    {
      title: 'My List (Summer internship project)',
      description: `A simple platform to share your passion by creating lists and sharing them with other users.`,
      type: 'Academic',
      imgSrc: '',
      href: 'https://mylist-f82d6.firebaseapp.com',
      github: 'https://github.com/ayoub3bidi/mylist',
      techStack: ['Vue', 'Bootstrap', 'Firebase'],
    },
    {
      title: 'GFA Phones',
      description: `A simple e-commerce platform for phones and accessories.`,
      type: 'Academic',
      imgSrc: '',
      href: '',
      github: 'https://github.com/ayoub3bidi/GFA-phones',
      techStack: ['Angular', 'Bootstrap ', 'Adobe XD', "Balsamique", "FastAPI", "MySQL"],
    },
    {
      title: 'My Heroes',
      description: `A minimalist website that can display mini-biographies about 20 programmers who made the internet as we know it today.`,
      type: 'Open-source',
      imgSrc: '',
      href: 'https://ayoub3bidi.github.io/myheroes/',
      github: 'https://github.com/ayoub3bidi/myheroes',
      techStack: ['Vue', 'Bootstrap'],
    },
    {
      title: 'Quotes',
      description: `A website that can display random inspirational quotes from a public Api.`,
      type: 'Open-source',
      imgSrc: '',
      href: 'https://ayoub3bidi.github.io/Quotes',
      github: 'https://github.com/ayoub3bidi/Quotes',
      techStack: ['Bootstrap', 'Javascript', 'Public API'],
    },
    {
      title: 'My Favorite LOL Champion',
      description: `A minimalist website for my favorite League of Legends champion Ekko.`,
      type: 'Open-source',
      imgSrc: '',
      href: 'https://ayoub3bidi.github.io/myFavoriteLolChampion/',
      github: 'https://github.com/ayoub3bidi/myFavoriteLolChampion',
      techStack: ['HTML', 'Bootstrap', 'Javascript'],
    },
    {
      title: 'Dokkōdō',
      description: `A minimalist website that can display Musashi's 21 principles for those who walk alone in this life.`,
      type: 'Open-source',
      imgSrc: '',
      href: 'https://ayoub3bidi.github.io/Dokkodo',
      github: 'https://github.com/ayoub3bidi/Dokkodo',
      techStack: ['JavaScript', 'CSS', 'Webslides'],
    },
  ]
  
  export default projectsData